name: CI/CD for SenegalID-OCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask opencv-python pytesseract werkzeug numpy Pillow

    - name: Run your application
      run: |
        # If you want to run tests, include that command here
        # For example, if you have a test script:
        # python -m unittest discover
        echo "Running SenegalID-OCR API"
        python app.py  # Replace with the command to run your API

    - name: Cleanup
      run: |
        echo "Cleanup if necessary"
